// ============================================================
// ARCHIVO DE CONTENIDO — Editá acá para actualizar el sitio
// ============================================================
//
// ┌──────────────────────────────────────────────────────────┐
// │  CÓMO ACTUALIZAR EL SITIO (no necesitás Cloud Shell)      │
// │                                                          │
// │  1. Editá este archivo (en GitHub.com, ícono lápiz)      │
// │  2. Abajo de todo: "Commit changes"                      │
// │  3. El sitio se publica SOLO en 1-2 minutos              │
// │     (lo hace GitHub Actions -> Firebase, automático)     │
// │                                                          │
// │  NUNCA edites .github/workflows/deploy.yml               │
// │  Ese archivo dispara el deploy y es sensible a los       │
// │  espacios. Si se rompe, el sitio deja de publicarse.     │
// └──────────────────────────────────────────────────────────┘
//
// ── AGREGAR UNA PRÓXIMA CHARLA EN VIVO ──────────────────────
//   Buscá el array PROXIMAS_CHARLAS y agregá un bloque:
//     {
//       titulo: "Nombre de la charla",
//       disertante: "Nombre Apellido",
//       fecha: "2026-07-15",            // YYYY-MM-DD (o "" si no querés mostrarla)
//       dia: "Lunes 15 de julio",       // texto libre
//       hora: "",
//       categoria: "pequeños-animales", // pequeños-animales | bovinos | equinos | no-convencionales
//     },
//
// ── PASAR UNA CHARLA YA DADA A "GRABACIONES" ────────────────
//   Borrala de PROXIMAS_CHARLAS y agregala en GRABACIONES con
//   un id nuevo (el próximo libre es el 143):
//     {
//       id: 143,
//       titulo: "Ingreso inteligente al Feedlot: manejo sanitario y adaptación — Parte 1",
//       disertante: "Med. Vet. Fernando Grippaldi",
//       fecha: "",
//       categoria: "bovinos",
//       subcategoria: "Neurología",      // opcional
//       descripcion: "",
//       imagen: "img/fernando-grippaldi.jpg",
//       duracion: "",
//     },
//
// ── CAMBIAR DATOS GENERALES (WhatsApp, sponsor, etc.) ───────
//   Todo está acá abajo en SITE_CONFIG.
// ============================================================

const SITE_CONFIG = {
  nombre: "Canal Veterinario",
  subtitulo: "Capacitación veterinaria profesional",
  telegramLink: "https://t.me/CANALVETCURSOS",
  instagram: "https://instagram.com/canalveterinario",

  // ── WhatsApp para consultas (poné tu número con código de país, sin + ni espacios) ──
  whatsapp: "5491131761770",
  whatsappMensaje: "Hola! Quiero más información sobre las suscripciones del Canal Veterinario",

  // ── Formulario de inscripción (Google Forms) ──
  formulario: "https://docs.google.com/forms/d/e/1FAIpQLSdskfP8fwAPF4qaEzPiKmUcLxFOW3OGJj9jpbEEEoGMqHl-Mw/viewform",

  // ── Cada cuántos segundos reaparece el cartel de suscripción (0 = desactivado) ──
  popupCadaSegundos: 200,

  // ── Personas en la comunidad (veterinarios, especialistas, etc.) ──
  comunidad: 298,

  // ── Sponsor (banner fijo) ──
  sponsorNombre: "Laboratorio Buenos Aires — LBsAs",
  sponsorSlogan: "Diagnóstico Veterinario",
  sponsorTel: "011 4573-3731",
  sponsorWA: "5491159540359",
  sponsorDir: "Av. De los Constituyentes 4884, CABA",
  sponsorEmail: "laboratoriobuenosaires@hotmail.com",

  // ── Contacto para nuevos sponsors y colaboradores ──
  contactoSponsor: "5491131761770",
  contactoColaborador: "5491131761770",

  // ── Google Analytics 4 (gratis) ──
  // Pegá acá tu código de medición y listo. Lo sacás gratis en analytics.google.com
  // → Admin → Flujos de datos → tu sitio. Mientras esté vacío, no se carga nada.
  // Ejemplo: "G-ABC1234XYZ"
  analyticsId: "",
};

// ============================================================
// PLANES DE SUSCRIPCIÓN — editá precios y links acá
// ============================================================

const PLANES = [
  {
    id: "basica",
    nombre: "Básica",
    destacado: false,
    precioARS: "5.300",
    precioUSD: "10",
    ideal: "Ideal para estudiantes y veterinarios recién recibidos",
    beneficios: [
      "Acceso a charlas del mes actual + anterior",
      "Charlas en vivo incluidas",
      "Comunidad en Telegram",
    ],
    linkMercadoPago: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c9380848eba1011018ec4e6a7f40858",
    linkPayPal: "https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-32347768RK031242LMZN2W3A&utm_source=bio_libre&utm_medium=Referral&utm_campaign=general_link",
  },
  {
    id: "premium",
    nombre: "Premium",
    destacado: true,
    precioARS: "8.600",
    precioUSD: "15",
    ideal: "Ideal para actualización profesional continua",
    beneficios: [
      "Acceso a TODAS las charlas (130+)",
      "Todas las grabaciones del archivo histórico",
      "Charlas en vivo incluidas",
      "Comunidad en Telegram",
    ],
    linkMercadoPago: "https://www.mercadopago.com.ar/subscriptions/checkout?preapproval_plan_id=2c9380849082b3f601909378c89f04f6",
    linkPayPal: "https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-84P62261SM765833JM2HJN3Q&utm_source=bio_libre&utm_medium=Referral&utm_campaign=general_link",
  },
];

// ============================================================
// PRÓXIMAS CHARLAS EN VIVO
// ============================================================

const PROXIMAS_CHARLAS = [
  {
    titulo: "Hipotiroidismo — Parte 2",
    disertante: "Carolina Vecino",
    fecha: "2026-06-08",
    dia: "Lunes 8 de junio",
    hora: "",
    categoria: "pequeños-animales",
    imagen: "img/carolina-vecino.png",
  },
  {
    titulo: "Gingivoestomatitis crónica felina y Calicivirus — Tratamientos Parte 2",
    disertante: "Natalia Luka",
    fecha: "2026-06-15",
    dia: "Lunes 15 de junio",
    hora: "",
    categoria: "pequeños-animales",
    imagen: "img/natalia-luka.jpg",
  },
  {
    titulo: "Histopatología veterinaria: el puente entre la clínica y el diagnóstico definitivo",
    disertante: "Matías Caverzan",
    fecha: "2026-06-17",
    dia: "Miércoles 17 de junio",
    hora: "",
    categoria: "pequeños-animales",
    imagen: "img/matias-caverzan.jpg",
  },
  {
    titulo: "Biomecánica aplicada a las fases del paso en caballos. Parte 1",
    disertante: "Vet. José Adrián Iranzo",
    fecha: "2026-06-22",
    dia: "Lunes 22 de junio",
    hora: "",
    categoria: "equinos",
    imagen: "img/jose-iranzo.jpg",
  },
  {
    titulo: "Técnica quirúrgica aséptica: Asepsia y antisepsia",
    disertante: "Georgina Soledad Castro",
    fecha: "2026-06-24",
    dia: "Miércoles 24 de junio",
    hora: "",
    categoria: "pequeños-animales",
    imagen: "img/georgina-castro.jpg",
  },
  {
    titulo: "Mastectomía: Errores más frecuentes y conceptos quirúrgicos de resolución",
    disertante: "Damián Barón",
    fecha: "2026-06-29",
    dia: "Lunes 29 de junio",
    hora: "",
    categoria: "pequeños-animales",
    imagen: "img/damian-baron.jpg",
  },
];

// ============================================================
// GRABACIONES DISPONIBLES — Charlas ya realizadas
// ============================================================

const GRABACIONES = [

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — NEUROLOGÍA
  // ──────────────────────────────────────────────
  {
    id: 2,
    titulo: "Aproximación al paciente con crisis cerebrales. Parte 1",
    disertante: "Vet. Matías D'Elia",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Neurología",
    descripcion: "",
    imagen: "img/matias-delia.jpg",
    duracion: "",
  },
  {
    id: 3,
    titulo: "Aproximación al paciente con crisis cerebrales. Parte 2",
    disertante: "Vet. Matías D'Elia",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Neurología",
    descripcion: "",
    imagen: "img/matias-delia.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — OFTALMOLOGÍA
  // ──────────────────────────────────────────────
  {
    id: 4,
    titulo: "Anatomía clínica del ojo. Parte 1",
    disertante: "Santiago Parrinello",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Oftalmología",
    descripcion: "",
    imagen: "img/parrinello.png",
    duracion: "",
  },
  {
    id: 5,
    titulo: "Anatomía clínica del ojo. Parte 2",
    disertante: "Santiago Parrinello",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Oftalmología",
    descripcion: "",
    imagen: "img/parrinello.png",
    duracion: "",
  },
  {
    id: 6,
    titulo: "Consulta oftalmológica: ¿cómo la realizamos?",
    disertante: "Santiago Parrinello",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Oftalmología",
    descripcion: "",
    imagen: "img/parrinello.png",
    duracion: "",
  },
  {
    id: 7,
    titulo: "¿Qué pasa cuando mi paciente tiene úlcera de córnea?",
    disertante: "Santiago Parrinello",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Oftalmología",
    descripcion: "",
    imagen: "img/parrinello.png",
    duracion: "",
  },
  {
    id: 8,
    titulo: "Manejo clínico inicial de las úlceras de córnea. Parte 1",
    disertante: "Santiago Parrinello",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Oftalmología",
    descripcion: "",
    imagen: "img/parrinello.png",
    duracion: "",
  },
  {
    id: 10,
    titulo: "Anatomía clínica del ojo. Parte 3: importancia clínica de la irrigación e inervación del globo ocular y sus anexos",
    disertante: "Santiago Parrinello",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Oftalmología",
    descripcion: "",
    imagen: "img/parrinello.png",
    duracion: "",
  },
  {
    id: 11,
    titulo: "Manejo clínico inicial de las úlceras de córnea. Parte 2",
    disertante: "Santiago Parrinello",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Oftalmología",
    descripcion: "",
    imagen: "img/parrinello.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — ENFERMEDADES INFECCIOSAS
  // ──────────────────────────────────────────────
  {
    id: 13,
    titulo: "Esporotricosis zoonótica, desde la clínica al diagnóstico de laboratorio. Parte 1",
    disertante: "Dr. Alejandro Etchecopaz",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Enfermedades infecciosas",
    descripcion: "",
    imagen: "img/alejandro-etchecopaz.jpg",
    duracion: "",
  },
  {
    id: 14,
    titulo: "Esporotricosis zoonótica, desde la clínica al diagnóstico de laboratorio. Parte 2",
    disertante: "Dr. Alejandro Etchecopaz",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Enfermedades infecciosas",
    descripcion: "",
    imagen: "img/alejandro-etchecopaz.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — CLÍNICA GENERAL / EMERGENCIAS
  // ──────────────────────────────────────────────
  {
    id: 15,
    titulo: "Emergencias: cómo manejar pacientes críticos felinos (confirmar)",
    disertante: "MV. Juan Pablo Reina",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Clínica general / Emergencias",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 16,
    titulo: "Emergencias: Punciones a pericardio, pleura, abdomen y vejiga",
    disertante: "Vet. Fabián A. Moreno",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Clínica general / Emergencias",
    descripcion: "",
    imagen: "img/fabian-moreno.png",
    duracion: "",
  },
  {
    id: 17,
    titulo: "Emergencias: manejando al paciente felino crítico. Parte 2",
    disertante: "Vet. Fabián A. Moreno",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Clínica general / Emergencias",
    descripcion: "",
    imagen: "img/fabian-moreno.png",
    duracion: "",
  },
  {
    id: 19,
    titulo: "Triage en felinos",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Clínica general / Emergencias",
    descripcion: "",
    imagen: "",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — LABORATORIO / DIAGNÓSTICO
  // ──────────────────────────────────────────────
  {
    id: 20,
    titulo: "Interpretación de las enzimas hepáticas",
    disertante: "MV. Carlos A. Fernández",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Laboratorio / Diagnóstico",
    descripcion: "",
    imagen: "img/carlos-fernandez.png",
    duracion: "",
  },
  {
    id: 21,
    titulo: "Pruebas de laboratorio para el diagnóstico de enfermedades renales. Parte 1",
    disertante: "MV. Carlos A. Fernández",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Laboratorio / Diagnóstico",
    descripcion: "",
    imagen: "img/carlos-fernandez.png",
    duracion: "",
  },
  {
    id: 22,
    titulo: "Pruebas de laboratorio para el diagnóstico de enfermedades renales. Parte 2",
    disertante: "MV. Carlos A. Fernández",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Laboratorio / Diagnóstico",
    descripcion: "",
    imagen: "img/carlos-fernandez.png",
    duracion: "",
  },
  {
    id: 23,
    titulo: "Coagulograma y recuento de plaquetas",
    disertante: "MV. Carlos A. Fernández",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Laboratorio / Diagnóstico",
    descripcion: "",
    imagen: "img/carlos-fernandez.png",
    duracion: "",
  },
  {
    id: 24,
    titulo: "Pruebas de laboratorio para el diagnóstico de hiperadrenocorticismo. Parte 1",
    disertante: "MV. Carlos A. Fernández",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Laboratorio / Diagnóstico",
    descripcion: "",
    imagen: "img/carlos-fernandez.png",
    duracion: "",
  },
  {
    id: 25,
    titulo: "Análisis de orina: fundamentos y aplicaciones",
    disertante: "MV. Soledad Varela",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Laboratorio / Diagnóstico",
    descripcion: "",
    imagen: "img/soledad-varela.jpg",
    duracion: "",
  },
  {
    id: 26,
    titulo: "Manejo de efusiones",
    disertante: "Vet. Celeste Maistruarena",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Laboratorio / Diagnóstico",
    descripcion: "",
    imagen: "img/celeste-maistruarena.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — CARDIOLOGÍA
  // ──────────────────────────────────────────────
  {
    id: 27,
    titulo: "Cardiopatías frecuentes del paciente canino geronte. La rutina cardiológica: cómo estudiamos al corazón en nuestra consulta diaria",
    disertante: "Vet. Nicolás Porta",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Cardiología",
    descripcion: "",
    imagen: "img/nicolas-porta.png",
    duracion: "",
  },
  {
    id: 28,
    titulo: "La Rutina Cardiológica: cómo ordenar el estudio del corazón en consulta diaria",
    disertante: "Vet. Nicolás Porta",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Cardiología",
    descripcion: "",
    imagen: "img/nicolas-porta.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — URINARIO / NEFROLOGÍA
  // ──────────────────────────────────────────────
  {
    id: 29,
    titulo: "Enfermedad del tracto urinario inferior del gato. Parte 1",
    disertante: "Esp. MV. Viviana H. Ruidiaz",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Urinario / Nefrología",
    descripcion: "",
    imagen: "img/viviana-ruidiaz.jpg",
    duracion: "",
  },
  {
    id: 30,
    titulo: "Enfermedades del tracto urinario caudal del gato: ¿Cuál es el mayor desafío, diagnóstico o tratamiento? Segunda parte",
    disertante: "Esp. MV. Viviana H. Ruidiaz",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Urinario / Nefrología",
    descripcion: "",
    imagen: "img/viviana-ruidiaz.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — NUTRICIÓN CLÍNICA
  // ──────────────────────────────────────────────
  {
    id: 34,
    titulo: "Introducción a la nutrición BARF",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Nutrición clínica",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 35,
    titulo: "Prebióticos y Probióticos: claves para el equilibrio del microbioma, su modulación y la salud integral",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Nutrición clínica",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 36,
    titulo: "Nutrición clínica en diarrea aguda y crónica",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Nutrición clínica",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 37,
    titulo: "Manejo nutricional de la lipidosis felina",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Nutrición clínica",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 38,
    titulo: "Intervenciones dietarias en el sobrepeso de pequeños animales",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Nutrición clínica",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 39,
    titulo: "Manejo nutricional y farmacológico de la IPE (insuficiencia pancreática exocrina)",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Nutrición clínica",
    descripcion: "",
    imagen: "",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — FARMACOLOGÍA / ANESTESIA / ANALGESIA
  // ──────────────────────────────────────────────
  {
    id: 42,
    titulo: "Manejo del paciente diabético. Parte 1",
    disertante: "Vet. Carolina V. Vecino",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Farmacología / Anestesia / Analgesia",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 43,
    titulo: "Manejo del paciente diabético. Parte 2",
    disertante: "Vet. Carolina V. Vecino",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Farmacología / Anestesia / Analgesia",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 44,
    titulo: "Antibióticos en pequeños animales y felinos: generalidades y clasificación. Parte 1",
    disertante: "Vet. Ximena Doxandabarat",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Farmacología / Anestesia / Analgesia",
    descripcion: "",
    imagen: "img/ximena-doxandabarat.jpg",
    duracion: "",
  },
  {
    id: 45,
    titulo: "Antibióticos en pequeños animales y felinos: generalidades y clasificación. Parte 2",
    disertante: "Vet. Ximena Doxandabarat",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Farmacología / Anestesia / Analgesia",
    descripcion: "",
    imagen: "img/ximena-doxandabarat.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — ORTOPEDIA / REHABILITACIÓN
  // ──────────────────────────────────────────────
  {
    id: 46,
    titulo: "Rehabilitación en pequeños animales",
    disertante: "Vet. Flor de Prade",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Ortopedia / Rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 47,
    titulo: "Rehabilitación de ligamento cruzado en caninos. Parte 1",
    disertante: "Vet. Flor de Prade",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Ortopedia / Rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 48,
    titulo: "Rehabilitación de ligamento cruzado en caninos. Parte 2",
    disertante: "Vet. Flor de Prade",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Ortopedia / Rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 49,
    titulo: "Rehabilitación en pequeños animales. Parte 3",
    disertante: "Vet. Flor de Prade",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Ortopedia / Rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 53,
    titulo: "Carritos ortopédicos",
    disertante: "Vet. Flor de Prade",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Ortopedia / Rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — ENDOCRINOLOGÍA
  // ──────────────────────────────────────────────
  {
    id: 54,
    titulo: "Cetoacidosis diabética",
    disertante: "Vet. Carolina Vecino",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Endocrinología",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 55,
    titulo: "Enfermedad de Addison",
    disertante: "Vet. Carolina Vecino",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Endocrinología",
    descripcion: "",
    imagen: "",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — ONCOLOGÍA / DERMATOLOGÍA
  // ──────────────────────────────────────────────
  {
    id: 57,
    titulo: "Carcinoma de células escamosas: desde la histopatología a la clínica",
    disertante: "MV. Matías Caverzan",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Oncología / Dermatología",
    descripcion: "",
    imagen: "img/matias-caverzan.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — IMAGENOLOGÍA
  // ──────────────────────────────────────────────
  {
    id: 58,
    titulo: "Ecografía de la Cavidad abdominal para los que empiezan. Primera parte",
    disertante: "Esp. Sabrina Vega",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Imagenología",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 59,
    titulo: "Ecografía como método diagnóstico en pacientes con vómito y diarrea. Parte 1",
    disertante: "Esp. Sabrina Vega",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Imagenología",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 60,
    titulo: "Ecografía como método diagnóstico en pacientes con vómito y diarrea. Parte 2",
    disertante: "Esp. Sabrina Vega",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Imagenología",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 61,
    titulo: "Ultrasonografía diagnóstica en felinos con ictericia (Parte 2)",
    disertante: "Esp. Sabrina Vega",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Imagenología",
    descripcion: "",
    imagen: "",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — CIRUGÍA
  // ──────────────────────────────────────────────
  {
    id: 63,
    titulo: "Aproximación a la cirugía gastrointestinal",
    disertante: "Vet. Leonardo Madriaga",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Cirugía",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 64,
    titulo: "Introducción a la cirugía de tejido blando de tórax y extremidades",
    disertante: "Vet. Leonardo Madriaga",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Cirugía",
    descripcion: "",
    imagen: "",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // PEQUEÑOS ANIMALES — INFECTOLOGÍA
  // ──────────────────────────────────────────────

  // ──────────────────────────────────────────────
  // EQUINOS — ANATOMÍA / BIOMECÁNICA / APARATO LOCOMOTOR
  // ──────────────────────────────────────────────
  {
    id: 66,
    titulo: "Aparato de sostén y sistema fibroelástico del equino",
    disertante: "Dr. Carlos Blanco",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Anatomía / Biomecánica / Aparato locomotor",
    descripcion: "",
    imagen: "img/carlos-blanco.png",
    duracion: "",
  },
  {
    id: 68,
    titulo: "Anatomía e imagen del aparato locomotor: diagnóstico por imágenes. Parte 1",
    disertante: "Vet. José Adrián Iranzo",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Anatomía / Biomecánica / Aparato locomotor",
    descripcion: "",
    imagen: "img/jose-iranzo.jpg",
    duracion: "",
  },
  {
    id: 69,
    titulo: "Regiones del sistema musculoesquelético: diagnóstico y tratamiento. Parte 2",
    disertante: "Vet. José Adrián Iranzo",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Anatomía / Biomecánica / Aparato locomotor",
    descripcion: "",
    imagen: "img/jose-iranzo.jpg",
    duracion: "",
  },
  {
    id: 70,
    titulo: "Análisis del pie para uso veterinario y herraje. Parte 1",
    disertante: "Vet. Verónica Aversa",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Anatomía / Biomecánica / Aparato locomotor",
    descripcion: "",
    imagen: "img/veronica-riveros.jpg",
    duracion: "",
  },
  {
    id: 71,
    titulo: "Anatomía y biomecánica del aparato locomotor en equinos. Parte 2",
    disertante: "Vet. Verónica Aversa",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Anatomía / Biomecánica / Aparato locomotor",
    descripcion: "",
    imagen: "img/veronica-riveros.jpg",
    duracion: "",
  },
  {
    id: 72,
    titulo: "Diagnóstico por imágenes: signos radiológicos y ultrasonográficos en la región del pie (confirmar)",
    disertante: "Vet. José Adrián Iranzo",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Anatomía / Biomecánica / Aparato locomotor",
    descripcion: "",
    imagen: "img/jose-iranzo.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // EQUINOS — DIAGNÓSTICO POR IMÁGENES
  // ──────────────────────────────────────────────
  {
    id: 74,
    titulo: "Diagnóstico ecográfico de las patologías del pie equino. Parte 1",
    disertante: "Dra. Valeria Arpón",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Diagnóstico por imágenes",
    descripcion: "",
    imagen: "img/valeria-arpon.jpg",
    duracion: "",
  },
  {
    id: 75,
    titulo: "Diagnóstico ecográfico de las patologías del pie equino. Parte 2",
    disertante: "Dra. Valeria Arpón",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Diagnóstico por imágenes",
    descripcion: "",
    imagen: "img/valeria-arpon.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // EQUINOS — ANESTESIA / SEDACIÓN / FARMACOLOGÍA
  // ──────────────────────────────────────────────

  // ──────────────────────────────────────────────
  // EQUINOS — REHABILITACIÓN / DEPORTE / TERAPIAS
  // ──────────────────────────────────────────────
  {
    id: 78,
    titulo: "Fisioterapia en el equino deportivo. Parte 1",
    disertante: "MV. Florencia de Prade",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Rehabilitación / Deporte / Terapias",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 79,
    titulo: "Fisioterapia en el equino deportivo. Parte 2",
    disertante: "MV. Florencia de Prade",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Rehabilitación / Deporte / Terapias",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 81,
    titulo: "Iluminando las claudicaciones oscuras. Parte 1",
    disertante: "MV. José Adrián Iranzo",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Rehabilitación / Deporte / Terapias",
    descripcion: "",
    imagen: "img/jose-iranzo.jpg",
    duracion: "",
  },
  {
    id: 82,
    titulo: "Iluminando las claudicaciones oscuras. Parte 2",
    disertante: "MV. José Adrián Iranzo",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Rehabilitación / Deporte / Terapias",
    descripcion: "",
    imagen: "img/jose-iranzo.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // EQUINOS — TERAPIAS COMPLEMENTARIAS
  // ──────────────────────────────────────────────
  {
    id: 83,
    titulo: "Introducción a las corrientes eléctricas en equinos. Parte 1",
    disertante: "Vet. Florencia de Priede",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Terapias complementarias",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 84,
    titulo: "Introducción a las corrientes eléctricas en equinos. Parte 2",
    disertante: "Vet. Florencia de Priede",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Terapias complementarias",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // EQUINOS — VÍAS AÉREAS / ENDOSCOPÍA / LARINGE
  // ──────────────────────────────────────────────
  {
    id: 85,
    titulo: "Endoscopía como herramienta diagnóstica en equinos con diferentes problemas en las vías aéreas",
    disertante: "MV. Ramón Andrés López",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Vías aéreas / Endoscopía / Laringe",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 86,
    titulo: "Resolución diagnóstica por endoscopía de vías aéreas superiores",
    disertante: "MV. Ramón Andrés López",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Vías aéreas / Endoscopía / Laringe",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 87,
    titulo: "Endoscopía de las vías aéreas superiores en equinos",
    disertante: "Vet. Fabián A. Moreno",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Vías aéreas / Endoscopía / Laringe",
    descripcion: "",
    imagen: "img/fabian-moreno.png",
    duracion: "",
  },
  {
    id: 88,
    titulo: "Endoscopía Gástrica en equinos",
    disertante: "Vet. Fabián A. Moreno",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Vías aéreas / Endoscopía / Laringe",
    descripcion: "",
    imagen: "img/fabian-moreno.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // EQUINOS — REPRODUCCIÓN
  // ──────────────────────────────────────────────

  // ──────────────────────────────────────────────
  // EQUINOS — OFTALMOLOGÍA
  // ──────────────────────────────────────────────
  {
    id: 90,
    titulo: "Déficit visual en equino",
    disertante: "Dr. Gustavo Zapata",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Oftalmología",
    descripcion: "",
    imagen: "img/gustavo-zapata.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // EQUINOS — ODONTOLOGÍA
  // ──────────────────────────────────────────────
  {
    id: 91,
    titulo: "Conceptos básicos de odontología en equinos",
    disertante: "MV. Miguel A. Mathius",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Odontología",
    descripcion: "",
    imagen: "img/miguel.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // BOVINOS — CLÍNICA / EMERGENCIAS / MANEJO SANITARIO
  // ──────────────────────────────────────────────
  {
    id: 92,
    titulo: "Diagnóstico y tratamiento de neumonías y diarreas en terneros",
    disertante: "MV. Juan Duque",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Clínica / Emergencias / Manejo sanitario",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 94,
    titulo: "Principales enfermedades de la vaca post parto",
    disertante: "MV. Juan Duque",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Clínica / Emergencias / Manejo sanitario",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 95,
    titulo: "Enfermedades infecciosas de interés en la reproducción bovina",
    disertante: "MV. Juan Duque",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Clínica / Emergencias / Manejo sanitario",
    descripcion: "",
    imagen: "",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // BOVINOS — REPRODUCCIÓN / OBSTETRICIA
  // ──────────────────────────────────────────────
  {
    id: 96,
    titulo: "Atención del parto en producción bovina",
    disertante: "MV. Lucio Campura",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Reproducción / Obstetricia",
    descripcion: "",
    imagen: "img/lucio-campora.png",
    duracion: "",
  },
  {
    id: 100,
    titulo: "Enfermedades uterinas en bovinos lecheros: endometritis y descarga vaginal purulenta. Parte 2",
    disertante: "MV. Lucio Campura",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Reproducción / Obstetricia",
    descripcion: "",
    imagen: "img/lucio-campora.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // MAYO 2026
  // ──────────────────────────────────────────────
  {
    id: 101,
    titulo: "Gingivoestomatitis crónica felina y Calicivirus — Fisiopatología. Parte 1",
    disertante: "Dra. Natalia Luka",
    fecha: "2026-05-11",
    categoria: "pequeños-animales",
    subcategoria: "Medicina interna",
    descripcion: "Rol del Calicivirus en la gingivoestomatitis crónica felina: mecanismos inmunológicos y fisiopatología.",
    imagen: "img/natalia-luka.jpg",
    duracion: "",
  },
  {
    id: 102,
    titulo: "Hipotiroidismo canino — Parte 1",
    disertante: "Dra. Carolina Vecino",
    fecha: "2026-05-18",
    categoria: "pequeños-animales",
    subcategoria: "Endocrinología",
    descripcion: "Fisiopatología, presentación clínica y diagnóstico del hipotiroidismo canino.",
    imagen: "",
    duracion: "",
  },
  {
    id: 103,
    titulo: "Linfoma canino: puntos clave",
    disertante: "Dra. Fernanda Ferreira",
    fecha: "2026-05-20",
    categoria: "pequeños-animales",
    subcategoria: "Oncología",
    descripcion: "Clasificación, diagnóstico citológico/histológico, estadificación y opciones terapéuticas actuales.",
    imagen: "img/fernanda-ferreira.jpg",
    duracion: "",
  },
  {
    id: 104,
    titulo: "Principios del manejo transfusional en felinos",
    disertante: "Dra. Celeste Maistruarena",
    fecha: "2026-05-25",
    categoria: "pequeños-animales",
    subcategoria: "Medicina de urgencias",
    descripcion: "Indicaciones, grupos sanguíneos felinos, técnica de transfusión y monitoreo de complicaciones.",
    imagen: "img/celeste-maistruarena.jpg",
    duracion: "",
  },
  {
    id: 105,
    titulo: "Enfermedades metabólicas carenciales en bovinos — Región central",
    disertante: "Dr. Germán Cantón",
    fecha: "2026-05-26",
    categoria: "bovinos",
    subcategoria: "Nutrición y metabolismo",
    descripcion: "Diagnóstico y manejo de las principales carencias minerales y vitamínicas en rodeos de la región central de Argentina.",
    imagen: "img/german-canton.jpg",
    duracion: "",
  },
  {
    id: 106,
    titulo: "El ABC del virus en la diarrea viral bovina",
    disertante: "Dr. Darío Malacari",
    fecha: "2026-05-31",
    categoria: "bovinos",
    subcategoria: "Enfermedades infecciosas",
    descripcion: "Fundamentos virológicos de la DVB: agente, patogenia y estrategias de control.",
    imagen: "img/dario-malacari.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // BOVINOS — PRODUCCIÓN DEL RODEO
  // ──────────────────────────────────────────────
  {
    id: 107,
    titulo: "Sanidad y producción en el feedlot. Parte 1",
    disertante: "Med. Vet. Fernando Grippaldi",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Producción del rodeo",
    descripcion: "",
    imagen: "img/fernando-grippaldi.jpg",
    duracion: "",
  },
  {
    id: 108,
    titulo: "Sanidad y Recepción en Feedlot — Parte 2",
    disertante: "Med. Vet. Fernando Grippaldi",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Producción del rodeo",
    descripcion: "",
    imagen: "img/fernando-grippaldi.jpg",
    duracion: "",
  },
  {
    id: 109,
    titulo: "Sanidad y producción en el feedlot. Parte 3",
    disertante: "Med. Vet. Fernando Grippaldi",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Producción del rodeo",
    descripcion: "",
    imagen: "img/fernando-grippaldi.jpg",
    duracion: "",
  },
  {
    id: 110,
    titulo: "Destete precoz",
    disertante: "Med. Vet. Fernando Grippaldi",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Producción del rodeo",
    descripcion: "",
    imagen: "img/fernando-grippaldi.jpg",
    duracion: "",
  },
  {
    id: 111,
    titulo: "Manejo en la guachera. Parte 1",
    disertante: "MV. Lucio Campura",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Producción del rodeo",
    descripcion: "",
    imagen: "img/lucio-campora.png",
    duracion: "",
  },
  {
    id: 112,
    titulo: "Manejo en la guachera. Parte 2",
    disertante: "MV. Lucio Campura",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Producción del rodeo",
    descripcion: "",
    imagen: "img/lucio-campora.png",
    duracion: "",
  },
  {
    id: 113,
    titulo: "Corrección mineral en vaca de cría. Sales que bajan la presión",
    disertante: "Med. Vet. Fernando Grippaldi",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Producción del rodeo",
    descripcion: "",
    imagen: "img/fernando-grippaldi.jpg",
    duracion: "",
  },
  {
    id: 114,
    titulo: "Lectura de comederos e interpretación de bostas",
    disertante: "MV. Lucio Campura",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Producción del rodeo",
    descripcion: "",
    imagen: "img/lucio-campora.png",
    duracion: "",
  },
  {
    id: 115,
    titulo: "Manejo táctico-dinámico. Parte 1",
    disertante: "Med. Vet. Fernando Grippaldi",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Producción del rodeo",
    descripcion: "",
    imagen: "img/fernando-grippaldi.jpg",
    duracion: "",
  },
  {
    id: 116,
    titulo: "Corrección integral en rodeo de cría. Parte 2 (confirmar)",
    disertante: "MV. Juan Duque",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Producción del rodeo",
    descripcion: "",
    imagen: "",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // BOVINOS — METABOLISMO / NUTRICIÓN / FISIOPATOLOGÍA
  // ──────────────────────────────────────────────
  {
    id: 117,
    titulo: "Fisiopatología de la vaca en el período periparto (confirmar)",
    disertante: "MV. Lucio Campura",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Metabolismo / Nutrición / Fisiopatología",
    descripcion: "",
    imagen: "img/lucio-campora.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // NO CONVENCIONALES — GENERALIDADES
  // ──────────────────────────────────────────────
  {
    id: 118,
    titulo: "Ser veterinario de especies no tradicionales en una clínica privada",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Generalidades",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },
  {
    id: 119,
    titulo: "Laboratorio en la clínica de exóticos",
    disertante: "Juan Carlos Troiano",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Generalidades",
    descripcion: "",
    imagen: "img/juan-carlos-troiano.png",
    duracion: "",
  },
  {
    id: 120,
    titulo: "Toma de muestras sanguíneas en animales no tradicionales",
    disertante: "Juan Carlos Troiano",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Generalidades",
    descripcion: "",
    imagen: "img/juan-carlos-troiano.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // NO CONVENCIONALES — PEQUEÑOS MAMÍFEROS
  // ──────────────────────────────────────────────
  {
    id: 121,
    titulo: "Medicina de la comadreja overa",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Pequeños mamíferos",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },
  {
    id: 122,
    titulo: "Aproximación a la Medicina de Petauros",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Pequeños mamíferos",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },
  {
    id: 123,
    titulo: "Medicina en erizo pigmeo africano",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Pequeños mamíferos",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },
  {
    id: 124,
    titulo: "Patologías dentales en conejos y roedores",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Pequeños mamíferos",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },
  {
    id: 125,
    titulo: "Medicina en erizo pigmeo africano. Parte 2",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Pequeños mamíferos",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },
  {
    id: 126,
    titulo: "Patologías frecuentes en la clínica de hurones domésticos",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Pequeños mamíferos",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // NO CONVENCIONALES — REPTILES
  // ──────────────────────────────────────────────
  {
    id: 127,
    titulo: "Medicina en erizo pigmeo africano. Anestesia y cirugía",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Reptiles",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },
  {
    id: 128,
    titulo: "Casos quirúrgicos en reptiles. Parte 1",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Reptiles",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },
  {
    id: 129,
    titulo: "Principios de anestesia y cirugía en serpientes y lagartos. Parte 3",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Reptiles",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // NO CONVENCIONALES — AVES
  // ──────────────────────────────────────────────
  {
    id: 130,
    titulo: "Actualización en psitacosis",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "Aves",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // ABRIL 2026
  // ──────────────────────────────────────────────
  {
    id: 131,
    titulo: "Ingreso inteligente al Feedlot: manejo sanitario y adaptación — Parte 2",
    disertante: "Med. Vet. Fernando Grippaldi",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Nutrición y metabolismo",
    descripcion: "",
    imagen: "img/fernando-grippaldi.jpg",
    duracion: "",
  },
  {
    id: 132,
    titulo: "Ultrasonografía de la región ventral del cuello: Ecografía normal — Parte 2",
    disertante: "Sabrina Vega",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Diagnóstico por imágenes",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 133,
    titulo: "Manejo del rodeo de cría: Charla desde la experiencia a campo",
    disertante: "Paula Lorena Sosa Kardel",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Reproducción",
    descripcion: "",
    imagen: "img/paula-sosa-kardel.jpg",
    duracion: "",
  },
  {
    id: 134,
    titulo: "Ultrasonografía de la región ventral del cuello: Ecografía patológica — Parte 3",
    disertante: "Sabrina Vega",
    fecha: "",
    categoria: "equinos",
    subcategoria: "Diagnóstico por imágenes",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 135,
    titulo: "Parvovirus en caninos y felinos: interpretación y diagnóstico",
    disertante: "Darío Malacari",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Enfermedades infecciosas",
    descripcion: "",
    imagen: "img/dario-malacari.jpg",
    duracion: "",
  },
  {
    id: 136,
    titulo: "Displasia de codo: diagnóstico y abordaje clínico",
    disertante: "Jonathan Bolaños",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Cirugía / Traumatología",
    descripcion: "",
    imagen: "img/jonathan-bolanos.jpg",
    duracion: "",
  },
  {
    id: 137,
    titulo: "PIF: claves prácticas en diagnóstico y tratamiento para el veterinario clínico",
    disertante: "Gabriela Despuys",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Enfermedades infecciosas",
    descripcion: "",
    imagen: "img/gabriela-despuys.jpg",
    duracion: "",
  },

  // ──────────────────────────────────────────────
  // MAYO 2026
  // ──────────────────────────────────────────────
  {
    id: 138,
    titulo: "Hipotiroidismo — Parte 1",
    disertante: "Carolina Vecino",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Endocrinología",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 140,
    titulo: "Principios del manejo transfusional en felinos",
    disertante: "Celeste Maistruarena",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "Clínica general / Emergencias",
    descripcion: "",
    imagen: "img/celeste-maistruarena.jpg",
    duracion: "",
  },
  {
    id: 142,
    titulo: "El ABC del virus en la diarrea viral bovina",
    disertante: "Darío Malacari",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "Enfermedades infecciosas",
    descripcion: "",
    imagen: "img/dario-malacari.jpg",
    duracion: "",
  },

  {
    id: 167,
    titulo: "Ejercicios terapéuticos para estimular la propiocepción",
    disertante: "Vet. Florencia de Priede",
    fecha: "",
    categoria: "equinos",
    subcategoria: "rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 168,
    titulo: "Cómo reconocer el dolor post operatorio en caninos",
    disertante: "Mv. Esp. Eduarda Esjaita",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "cirugía",
    descripcion: "",
    imagen: "img/eduarda-esjaita.jpg",
    duracion: "",
  },
  {
    id: 169,
    titulo: "Potenciación muscular en el equino deportivo",
    disertante: "Vet. Florencia de Priede",
    fecha: "",
    categoria: "equinos",
    subcategoria: "rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 170,
    titulo: "Principios de la anestesia general en bovino, a campo",
    disertante: "MV. Pablo Stagnetto",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "anestesia",
    descripcion: "",
    imagen: "img/pablo-stagnetto.jpg",
    duracion: "",
  },
  {
    id: 171,
    titulo: "Masoterapia en equinos. Parte 1",
    disertante: "Vet. Florencia de Priede",
    fecha: "",
    categoria: "equinos",
    subcategoria: "rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 172,
    titulo: "Masoterapia en equinos. Parte 2",
    disertante: "Vet. Florencia de Priede",
    fecha: "",
    categoria: "equinos",
    subcategoria: "rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 173,
    titulo: "Enfermedades reproductivas. Parte 1",
    disertante: "Mv. Lucio Campora",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "reproducción",
    descripcion: "",
    imagen: "img/lucio-campora.png",
    duracion: "",
  },
  {
    id: 174,
    titulo: "Cómo reconocer el dolor posoperatorio. Parte II: Felino",
    disertante: "Mv. Esp. Eduarda Esjaita",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "cirugía",
    descripcion: "",
    imagen: "img/eduarda-esjaita.jpg",
    duracion: "",
  },
  {
    id: 175,
    titulo: "Pruebas de laboratorio para el diagnóstico de hiperadrenocorticismo. Parte 2",
    disertante: "MV. Carlos A. Fernández",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "laboratorio",
    descripcion: "",
    imagen: "img/carlos-fernandez.png",
    duracion: "",
  },
  {
    id: 176,
    titulo: "Castración en equinos: opciones, complicaciones y su manejo",
    disertante: "Vet. Mauro Verna",
    fecha: "",
    categoria: "equinos",
    subcategoria: "cirugía",
    descripcion: "",
    imagen: "img/mauro-verna.png",
    duracion: "",
  },
  {
    id: 177,
    titulo: "Orina felina, un pequeño charco con pistas diagnósticas. Parte 1",
    disertante: "Esp. MV. Viviana H. Ruidiaz",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "laboratorio",
    descripcion: "",
    imagen: "img/viviana-ruidiaz.jpg",
    duracion: "",
  },
  {
    id: 179,
    titulo: "Ojo rojo como punto de partida de las enfermedades oftalmológicas",
    disertante: "Santiago Parrinello",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "oftalmología",
    descripcion: "",
    imagen: "img/parrinello.png",
    duracion: "",
  },
  {
    id: 181,
    titulo: "Aproximación al paciente felino crítico",
    disertante: "Vet. Celeste Maistruarena",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "medicina interna",
    descripcion: "",
    imagen: "img/celeste-maistruarena.jpg",
    duracion: "",
  },
  {
    id: 182,
    titulo: "Manejo del paciente alérgico",
    disertante: "MV. Pablo Manzuck",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "dermatología",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 183,
    titulo: "Lesiones en rodillas: ruptura de ligamento cruzado anterior y luxación patelar",
    disertante: "Dr. Jonatan Bolaños",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "ortopedia",
    descripcion: "",
    imagen: "img/jonathan-bolanos.jpg",
    duracion: "",
  },
  {
    id: 184,
    titulo: "Región cervical del equino: anatomía, biomecánica, síndrome cérvico-toraco-braquial y complejo de malformación cervical equina. Parte 1",
    disertante: "MV. José Adrián Iranzo",
    fecha: "",
    categoria: "equinos",
    subcategoria: "anatomía",
    descripcion: "",
    imagen: "img/jose-iranzo.jpg",
    duracion: "",
  },
  {
    id: 185,
    titulo: "Región cervical del equino: anatomía, biomecánica, síndrome cérvico-toraco-braquial y complejo de malformación cervical equina. Parte 2",
    disertante: "MV. José Adrián Iranzo",
    fecha: "",
    categoria: "equinos",
    subcategoria: "anatomía",
    descripcion: "",
    imagen: "img/jose-iranzo.jpg",
    duracion: "",
  },
  {
    id: 186,
    titulo: "Manejo del paciente con diabetes. Parte 2",
    disertante: "Vet. Carolina Vecino",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "endocrinología",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 187,
    titulo: "Ictericia en felinos",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "medicina interna",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 188,
    titulo: "Manejo del felino con obstrucción urinaria",
    disertante: "Vet. Celeste Maistruarena",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "urología",
    descripcion: "",
    imagen: "img/celeste-maistruarena.jpg",
    duracion: "",
  },
  {
    id: 189,
    titulo: "Manejo reproductivo de un rodeo lechero y seguimiento de la vaca desde el preparto, parto y liberación a servicio",
    disertante: "MV. Eugenio Sosa",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "reproducción",
    descripcion: "",
    imagen: "img/eugenio-sosa.jpg",
    duracion: "",
  },
  {
    id: 190,
    titulo: "Uso de monitores de actividad en reproducción bovina",
    disertante: "Mv. Lucio Campora",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "reproducción",
    descripcion: "",
    imagen: "img/lucio-campora.png",
    duracion: "",
  },
  {
    id: 191,
    titulo: "Mastocitoma canino, un desafío en la práctica clínica",
    disertante: "MV. Matías Caverzan",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "oncología",
    descripcion: "",
    imagen: "img/matias-caverzan.jpg",
    duracion: "",
  },
  {
    id: 192,
    titulo: "Uso de ortesis en rehabilitación de pequeños animales. Parte 2",
    disertante: "Vet. Florencia de Priede",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 193,
    titulo: "Introducción al servicio de resonancia — ENNA Neurodiagnóstico",
    disertante: "Ramiro Vidal y Piero Lovecchio",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "neurología",
    descripcion: "",
    imagen: "img/enna-neurodiagnostico.jpg",
    duracion: "",
  },
  {
    id: 194,
    titulo: "Enfermedades uterinas en bovinos lecheros: endometritis y descarga vaginal purulenta. Parte 1",
    disertante: "Mv. Lucio Campora",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "reproducción",
    descripcion: "",
    imagen: "img/lucio-campora.png",
    duracion: "",
  },
  {
    id: 195,
    titulo: "Homeostasis del calcio y fisiopatología de la hipocalcemia puerperal",
    disertante: "Mv. Lucio Campora",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "medicina interna",
    descripcion: "",
    imagen: "img/lucio-campora.png",
    duracion: "",
  },
  {
    id: 196,
    titulo: "Fármacos para sedación, analgesia y anestesia en equinos. Parte 1",
    disertante: "MV. Rocío Paola Álvarez",
    fecha: "",
    categoria: "equinos",
    subcategoria: "anestesia",
    descripcion: "",
    imagen: "img/rocio-alvarez.png",
    duracion: "",
  },
  {
    id: 197,
    titulo: "Fármacos para sedación, analgesia y anestesia en equinos. Parte 2",
    disertante: "MV. Rocío Paola Álvarez",
    fecha: "",
    categoria: "equinos",
    subcategoria: "anestesia",
    descripcion: "",
    imagen: "img/rocio-alvarez.png",
    duracion: "",
  },
  {
    id: 198,
    titulo: "Punción de médula ósea: indicaciones y técnica",
    disertante: "MV. Soledad Varela",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "laboratorio",
    descripcion: "",
    imagen: "img/soledad-varela.jpg",
    duracion: "",
  },
  {
    id: 199,
    titulo: "Diagnóstico ecográfico de patologías de la región del nudo",
    disertante: "Dra. Valeria Arpón",
    fecha: "",
    categoria: "equinos",
    subcategoria: "ecografía",
    descripcion: "",
    imagen: "img/valeria-arpon.jpg",
    duracion: "",
  },
  {
    id: 200,
    titulo: "Caso clínico: abordaje, protocolos y resolución en caninos",
    disertante: "Vet. Florencia de Priede",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "rehabilitación",
    descripcion: "",
    imagen: "img/florencia-de-priede.png",
    duracion: "",
  },
  {
    id: 201,
    titulo: "Síndrome de constipación felina: diagnóstico y tratamiento",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "medicina interna",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 202,
    titulo: "Hipoglucemias",
    disertante: "Vet. Carolina Vecino",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "endocrinología",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 203,
    titulo: "Casos quirúrgicos en reptiles. Parte 2",
    disertante: "MV. Nicolás Cohen",
    fecha: "",
    categoria: "no-convencionales",
    subcategoria: "cirugía",
    descripcion: "",
    imagen: "img/nicolas-cohen.png",
    duracion: "",
  },
  {
    id: 204,
    titulo: "Atención de la ternera recién nacida y manejo en los primeros 60 días",
    disertante: "MV. Eugenio Sosa",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "manejo",
    descripcion: "",
    imagen: "img/eugenio-sosa.jpg",
    duracion: "",
  },
  {
    id: 205,
    titulo: "Actualización en manejo de sepsis en felinos",
    disertante: "Vet. Celeste Maistruarena",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "medicina interna",
    descripcion: "",
    imagen: "img/celeste-maistruarena.jpg",
    duracion: "",
  },
  {
    id: 206,
    titulo: "Todo lo que se necesita saber sobre la dermatofitosis felina",
    disertante: "Dr. Alejandro Etchecopaz",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "dermatología",
    descripcion: "",
    imagen: "img/alejandro-etchecopaz.jpg",
    duracion: "",
  },
  {
    id: 207,
    titulo: "Prueba de diagnóstico para ehrlichiosis canina",
    disertante: "MV. Carlos A. Fernández",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "laboratorio",
    descripcion: "",
    imagen: "img/carlos-fernandez.png",
    duracion: "",
  },
  {
    id: 208,
    titulo: "Diagnóstico temprano de displasia de cadera y sus tratamientos",
    disertante: "Dr. Jonatan Bolaños",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "ortopedia",
    descripcion: "",
    imagen: "img/jonathan-bolanos.jpg",
    duracion: "",
  },
  {
    id: 209,
    titulo: "Neuro oftalmología para la clínica diaria",
    disertante: "Santiago Parrinello",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "oftalmología",
    descripcion: "",
    imagen: "img/parrinello.png",
    duracion: "",
  },
  {
    id: 210,
    titulo: "Nutrición en el síndrome senil",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "nutrición",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 211,
    titulo: "Merma tacto-Destete. Parte 1",
    disertante: "Med. Vet. Fernando Grippaldi",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "reproducción",
    descripcion: "",
    imagen: "img/fernando-grippaldi.jpg",
    duracion: "",
  },
  {
    id: 212,
    titulo: "Manejo nutricional de las hepatopatías",
    disertante: "Vet. Brenda Viñas",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "nutrición",
    descripcion: "",
    imagen: "",
    duracion: "",
  },
  {
    id: 213,
    titulo: "Antibióticos en heridas: explicado en casos clínicos",
    disertante: "Vet. Ximena Doxandabarat",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "farmacología",
    descripcion: "",
    imagen: "img/ximena-doxandabarat.jpg",
    duracion: "",
  },
  {
    id: 214,
    titulo: "Merma tacto-Destete. Parte 2",
    disertante: "Med. Vet. Fernando Grippaldi",
    fecha: "",
    categoria: "bovinos",
    subcategoria: "reproducción",
    descripcion: "",
    imagen: "img/fernando-grippaldi.jpg",
    duracion: "",
  },
  {
    id: 215,
    titulo: "Tres pacientes, una droga ¿mismo resultado?",
    disertante: "MV. Rocío Paola Álvarez",
    fecha: "",
    categoria: "equinos",
    subcategoria: "anestesia",
    descripcion: "",
    imagen: "img/rocio-alvarez.png",
    duracion: "",
  },
  {
    id: 216,
    titulo: "Leucemias inespecíficas",
    disertante: "MV. Soledad Varela",
    fecha: "",
    categoria: "pequeños-animales",
    subcategoria: "laboratorio",
    descripcion: "",
    imagen: "img/soledad-varela.jpg",
    duracion: "",
  },
];

// ============================================================
// CATEGORÍAS PRINCIPALES
// ============================================================

const CATEGORIAS = [
  { id: "todas",              nombre: "Todas",                   icono: "🔬" },
  { id: "pequeños-animales",  nombre: "Pequeños animales",       icono: "🐾" },
  { id: "bovinos",            nombre: "Bovinos",                 icono: "🐄" },
  { id: "equinos",            nombre: "Equinos",                 icono: "🐴" },
  { id: "no-convencionales",  nombre: "No convencionales",       icono: "🦜" },
];

// ============================================================
// SUBCATEGORÍAS (referencia — usá estos nombres en el campo
// "subcategoria" de cada charla para que queden consistentes)
// ============================================================
//
// Pequeños animales:
//   Neurología · Oftalmología · Enfermedades infecciosas
//   Clínica general / Emergencias · Laboratorio / Diagnóstico
//   Cardiología · Urinario / Nefrología · Nutrición clínica
//   Farmacología / Anestesia / Analgesia · Ortopedia / Rehabilitación
//   Endocrinología · Oncología / Dermatología · Imagenología
//   Cirugía · Infectología · Medicina interna · Medicina de urgencias · Oncología
//
// Bovinos:
//   Clínica / Emergencias / Manejo sanitario · Reproducción / Obstetricia
//   Producción del rodeo · Metabolismo / Nutrición / Fisiopatología
//   Enfermedades infecciosas · Nutrición y metabolismo
//
// Equinos:
//   Anatomía / Biomecánica / Aparato locomotor · Diagnóstico por imágenes
//   Anestesia / Sedación / Farmacología · Rehabilitación / Deporte / Terapias
//   Terapias complementarias · Vías aéreas / Endoscopía / Laringe
//   Reproducción · Oftalmología · Odontología
//
// No convencionales:
//   Generalidades · Pequeños mamíferos · Reptiles · Aves

// ============================================================
// RESUMEN DE GRABACIONES POR CATEGORÍA
// ============================================================
// Pequeños animales:  ids 1–65 + 101–104  = 69 grabaciones
// Equinos:            ids 66–91            = 26 grabaciones
// Bovinos:            ids 92–100 + 105–117 = 26 grabaciones
// No convencionales:  ids 118–130          = 13 grabaciones
// TOTAL:                                  = 130 grabaciones
// ============================================================
